// Generated by scripts/analyze-openings.mjs and build-opening-lines.mjs. Do not hand-edit.
export const OPENING_ANALYSIS = {
  "schema": 1,
  "engineId": "rapfi-nnue-3c94c2a-e32ad77",
  "sourceCommit": "3c94c2a976f24a0dd1c5517623e9ab6fffe66bd7",
  "networksCommit": "e32ad77a5364363b3e3a02b3f9e8610ade19ea98",
  "generatedAt": "2026-10-07T23:30:20.880Z",
  "settings": {
    "strength": 100,
    "thinkMs": 30000,
    "multiPv": 6,
    "threads": 2,
    "hashMB": 256,
    "concurrency": 3,
    "size": 15
  },
  "selection": {
    "maxWinRateLoss": 0.08,
    "maxScoreLoss": 200,
    "maxLines": 3,
    "symmetryDeduplicated": true
  },
  "openings": {
    "D01": {
      "renju": {
        "depth": 19,
        "elapsedMs": 30192,
        "variations": [
          {
            "moves": [
              112,
              97,
              82,
              96,
              95,
              98
            ],
            "rank": 1,
            "score": "-309",
            "blackWinRate": 0.82419,
            "depth": 21,
            "analysisPly": 5,
            "id": "renju-1"
          },
          {
            "moves": [
              112,
              97,
              82,
              81,
              96,
              98
            ],
            "rank": 2,
            "score": "-430",
            "blackWinRate": 0.895669,
            "depth": 19,
            "analysisPly": 3,
            "id": "renju-2"
          },
          {
            "moves": [
              112,
              97,
              82,
              96,
              95,
              81
            ],
            "rank": 2,
            "score": "-356",
            "blackWinRate": 0.855697,
            "depth": 21,
            "analysisPly": 5,
            "id": "renju-3"
          }
        ]
      },
      "freestyle": {
        "depth": 24,
        "elapsedMs": 30167,
        "variations": [
          {
            "moves": [
              112,
              97,
              82,
              111,
              96,
              80
            ],
            "rank": 1,
            "score": "-559",
            "blackWinRate": 0.942405,
            "depth": 24,
            "analysisPly": 3,
            "id": "freestyle-1"
          },
          {
            "moves": [
              112,
              97,
              82,
              81,
              113,
              111
            ],
            "rank": 2,
            "score": "-582",
            "blackWinRate": 0.9483386,
            "depth": 24,
            "analysisPly": 3,
            "id": "freestyle-2"
          },
          {
            "moves": [
              112,
              97,
              82,
              96,
              98,
              84
            ],
            "rank": 3,
            "score": "-595",
            "blackWinRate": 0.9514318,
            "depth": 24,
            "analysisPly": 3,
            "id": "freestyle-3"
          }
        ]
      }
    },
    "D02": {
      "renju": {
        "depth": 20,
        "elapsedMs": 30189,
        "variations": [
          {
            "moves": [
              112,
              97,
              83,
              113,
              81,
              82
            ],
            "rank": 1,
            "score": "-313",
            "blackWinRate": 0.82707,
            "depth": 20,
            "analysisPly": 3,
            "id": "renju-1"
          },
          {
            "moves": [
              112,
              97,
              83,
              98,
              96,
              82
            ],
            "rank": 2,
            "score": "-405",
            "blackWinRate": 0.883397,
            "depth": 20,
            "analysisPly": 3,
            "id": "renju-2"
          },
          {
            "moves": [
              112,
              97,
              83,
              114,
              81,
              98
            ],
            "rank": 3,
            "score": "-429",
            "blackWinRate": 0.895201,
            "depth": 20,
            "analysisPly": 3,
            "id": "renju-3"
          }
        ]
      },
      "freestyle": {
        "depth": 21,
        "elapsedMs": 30040,
        "variations": [
          {
            "moves": [
              112,
              97,
              83,
              84,
              96,
              128
            ],
            "rank": 1,
            "score": "-429",
            "blackWinRate": 0.895201,
            "depth": 21,
            "analysisPly": 3,
            "id": "freestyle-1"
          },
          {
            "moves": [
              112,
              97,
              83,
              98,
              96,
              81
            ],
            "rank": 2,
            "score": "-484",
            "blackWinRate": 0.9183398,
            "depth": 21,
            "analysisPly": 3,
            "id": "freestyle-2"
          },
          {
            "moves": [
              112,
              97,
              83,
              82,
              96,
              128
            ],
            "rank": 3,
            "score": "-507",
            "blackWinRate": 0.9265593,
            "depth": 21,
            "analysisPly": 3,
            "id": "freestyle-3"
          }
        ]
      }
    },
    "D03": {
      "renju": {
        "depth": 19,
        "elapsedMs": 28937,
        "variations": [
          {
            "moves": [
              112,
              97,
              84,
              98,
              96,
              128
            ],
            "rank": 1,
            "score": "-47",
            "blackWinRate": 0.558481,
            "depth": 19,
            "analysisPly": 5,
            "id": "renju-1"
          },
          {
            "moves": [
              112,
              97,
              84,
              98,
              113,
              114
            ],
            "rank": 2,
            "score": "0",
            "blackWinRate": 0.5,
            "depth": 21,
            "analysisPly": 4,
            "id": "renju-2"
          },
          {
            "moves": [
              112,
              97,
              84,
              98,
              83,
              81
            ],
            "rank": 3,
            "score": "-12",
            "blackWinRate": 0.485004,
            "depth": 21,
            "analysisPly": 4,
            "id": "renju-3"
          }
        ]
      },
      "freestyle": {
        "depth": 21,
        "elapsedMs": 30034,
        "variations": [
          {
            "moves": [
              112,
              97,
              84,
              98,
              113,
              114
            ],
            "rank": 1,
            "score": "411",
            "blackWinRate": 0.886452,
            "depth": 23,
            "analysisPly": 4,
            "id": "freestyle-1"
          },
          {
            "moves": [
              112,
              97,
              84,
              98,
              114,
              113
            ],
            "rank": 2,
            "score": "350",
            "blackWinRate": 0.851953,
            "depth": 23,
            "analysisPly": 4,
            "id": "freestyle-2"
          },
          {
            "moves": [
              112,
              97,
              84,
              98,
              100,
              68
            ],
            "rank": 3,
            "score": "344",
            "blackWinRate": 0.848129,
            "depth": 23,
            "analysisPly": 4,
            "id": "freestyle-3"
          }
        ]
      }
    },
    "D04": {
      "renju": {
        "depth": 18,
        "elapsedMs": 30079,
        "variations": [
          {
            "moves": [
              112,
              97,
              98,
              126,
              83,
              113
            ],
            "rank": 1,
            "score": "-352",
            "blackWinRate": 0.85321,
            "depth": 18,
            "analysisPly": 3,
            "id": "renju-1"
          },
          {
            "moves": [
              112,
              97,
              98,
              114,
              84,
              70
            ],
            "rank": 2,
            "score": "-452",
            "blackWinRate": 0.9055096,
            "depth": 18,
            "analysisPly": 3,
            "id": "renju-2"
          },
          {
            "moves": [
              112,
              97,
              98,
              113,
              126,
              140
            ],
            "rank": 3,
            "score": "-506",
            "blackWinRate": 0.9262184,
            "depth": 18,
            "analysisPly": 3,
            "id": "renju-3"
          }
        ]
      },
      "freestyle": {
        "depth": 22,
        "elapsedMs": 30043,
        "variations": [
          {
            "moves": [
              112,
              97,
              98,
              113,
              129,
              99
            ],
            "rank": 1,
            "score": "-M54",
            "blackWinRate": 1,
            "depth": 28,
            "analysisPly": 5,
            "id": "freestyle-1"
          },
          {
            "moves": [
              112,
              97,
              98,
              113,
              129,
              114
            ],
            "rank": 2,
            "score": "-M46",
            "blackWinRate": 1,
            "depth": 28,
            "analysisPly": 5,
            "id": "freestyle-2"
          },
          {
            "moves": [
              112,
              97,
              98,
              113,
              129,
              128
            ],
            "rank": 3,
            "score": "-M32",
            "blackWinRate": 1,
            "depth": 28,
            "analysisPly": 5,
            "id": "freestyle-3"
          }
        ]
      }
    },
    "D05": {
      "renju": {
        "depth": 19,
        "elapsedMs": 30061,
        "variations": [
          {
            "moves": [
              112,
              97,
              99,
              113,
              81,
              83
            ],
            "rank": 1,
            "score": "-313",
            "blackWinRate": 0.82707,
            "depth": 19,
            "analysisPly": 3,
            "id": "renju-1"
          },
          {
            "moves": [
              112,
              97,
              99,
              114,
              128,
              113
            ],
            "rank": 2,
            "score": "-347",
            "blackWinRate": 0.850051,
            "depth": 19,
            "analysisPly": 3,
            "id": "renju-2"
          },
          {
            "moves": [
              112,
              97,
              99,
              98,
              128,
              144
            ],
            "rank": 3,
            "score": "-366",
            "blackWinRate": 0.861762,
            "depth": 19,
            "analysisPly": 3,
            "id": "renju-3"
          }
        ]
      },
      "freestyle": {
        "depth": 21,
        "elapsedMs": 30050,
        "variations": [
          {
            "moves": [
              112,
              97,
              99,
              98,
              128,
              144
            ],
            "rank": 1,
            "score": "-455",
            "blackWinRate": 0.9067853,
            "depth": 21,
            "analysisPly": 3,
            "id": "freestyle-1"
          },
          {
            "moves": [
              112,
              97,
              99,
              128,
              83,
              130
            ],
            "rank": 2,
            "score": "-468",
            "blackWinRate": 0.9121361,
            "depth": 21,
            "analysisPly": 3,
            "id": "freestyle-2"
          },
          {
            "moves": [
              112,
              97,
              99,
              83,
              111,
              113
            ],
            "rank": 3,
            "score": "-521",
            "blackWinRate": 0.9311827,
            "depth": 21,
            "analysisPly": 3,
            "id": "freestyle-3"
          }
        ]
      }
    },
    "D06": {
      "renju": {
        "depth": 18,
        "elapsedMs": 30058,
        "variations": [
          {
            "moves": [
              112,
              97,
              113,
              128,
              126,
              98
            ],
            "rank": 1,
            "score": "-266",
            "blackWinRate": 0.790841,
            "depth": 18,
            "analysisPly": 3,
            "id": "renju-1"
          },
          {
            "moves": [
              112,
              97,
              113,
              98,
              96,
              111
            ],
            "rank": 2,
            "score": "-352",
            "blackWinRate": 0.85321,
            "depth": 18,
            "analysisPly": 3,
            "id": "renju-2"
          },
          {
            "moves": [
              112,
              97,
              113,
              114,
              128,
              143
            ],
            "rank": 3,
            "score": "-379",
            "blackWinRate": 0.869325,
            "depth": 18,
            "analysisPly": 3,
            "id": "renju-3"
          }
        ]
      },
      "freestyle": {
        "depth": 22,
        "elapsedMs": 30040,
        "variations": [
          {
            "moves": [
              112,
              97,
              113,
              128,
              99,
              114
            ],
            "rank": 1,
            "score": "-448",
            "blackWinRate": 0.9037845,
            "depth": 22,
            "analysisPly": 3,
            "id": "freestyle-1"
          },
          {
            "moves": [
              112,
              97,
              113,
              114,
              128,
              111
            ],
            "rank": 2,
            "score": "-486",
            "blackWinRate": 0.9190865,
            "depth": 22,
            "analysisPly": 3,
            "id": "freestyle-2"
          },
          {
            "moves": [
              112,
              97,
              113,
              111,
              125,
              127
            ],
            "rank": 3,
            "score": "-522",
            "blackWinRate": 0.9315024,
            "depth": 22,
            "analysisPly": 3,
            "id": "freestyle-3"
          }
        ]
      }
    },
    "D07": {
      "renju": {
        "depth": 18,
        "elapsedMs": 30074,
        "variations": [
          {
            "moves": [
              112,
              97,
              114,
              83,
              128,
              96
            ],
            "rank": 1,
            "score": "-M50",
            "blackWinRate": 1,
            "depth": 30,
            "analysisPly": 5,
            "id": "renju-1"
          },
          {
            "moves": [
              112,
              97,
              114,
              83,
              128,
              129
            ],
            "rank": 2,
            "score": "-M28",
            "blackWinRate": 1,
            "depth": 30,
            "analysisPly": 5,
            "id": "renju-2"
          },
          {
            "moves": [
              112,
              97,
              114,
              83,
              128,
              111
            ],
            "rank": 3,
            "score": "-M26",
            "blackWinRate": 1,
            "depth": 30,
            "analysisPly": 5,
            "id": "renju-3"
          }
        ]
      },
      "freestyle": {
        "depth": 24,
        "elapsedMs": 27856,
        "variations": [
          {
            "moves": [
              112,
              97,
              114,
              128,
              129,
              98
            ],
            "rank": 1,
            "score": "-525",
            "blackWinRate": 0.9324533,
            "depth": 24,
            "analysisPly": 3,
            "id": "freestyle-1"
          },
          {
            "moves": [
              112,
              97,
              114,
              111,
              83,
              113
            ],
            "rank": 2,
            "score": "-655",
            "blackWinRate": 0.9635611,
            "depth": 24,
            "analysisPly": 3,
            "id": "freestyle-2"
          },
          {
            "moves": [
              112,
              97,
              114,
              113,
              128,
              144
            ],
            "rank": 3,
            "score": "-720",
            "blackWinRate": 0.973403,
            "depth": 24,
            "analysisPly": 3,
            "id": "freestyle-3"
          }
        ]
      }
    },
    "D08": {
      "renju": {
        "depth": 19,
        "elapsedMs": 30069,
        "variations": [
          {
            "moves": [
              112,
              97,
              127,
              142,
              125,
              113
            ],
            "rank": 1,
            "score": "156",
            "blackWinRate": 0.68568,
            "depth": 22,
            "analysisPly": 4,
            "id": "renju-1"
          },
          {
            "moves": [
              112,
              97,
              127,
              142,
              96,
              128
            ],
            "rank": 2,
            "score": "145",
            "blackWinRate": 0.673707,
            "depth": 22,
            "analysisPly": 4,
            "id": "renju-2"
          },
          {
            "moves": [
              112,
              97,
              127,
              142,
              110,
              128
            ],
            "rank": 3,
            "score": "127",
            "blackWinRate": 0.653622,
            "depth": 22,
            "analysisPly": 4,
            "id": "renju-3"
          }
        ]
      },
      "freestyle": {
        "depth": 22,
        "elapsedMs": 28813,
        "variations": [
          {
            "moves": [
              112,
              97,
              127,
              141,
              128,
              111
            ],
            "rank": 1,
            "score": "-565",
            "blackWinRate": 0.9440119,
            "depth": 22,
            "analysisPly": 3,
            "id": "freestyle-1"
          },
          {
            "moves": [
              112,
              97,
              127,
              125,
              111,
              110
            ],
            "rank": 2,
            "score": "-605",
            "blackWinRate": 0.9536909,
            "depth": 22,
            "analysisPly": 3,
            "id": "freestyle-2"
          },
          {
            "moves": [
              112,
              97,
              127,
              142,
              128,
              126
            ],
            "rank": 3,
            "score": "-633",
            "blackWinRate": 0.9594957,
            "depth": 22,
            "analysisPly": 3,
            "id": "freestyle-3"
          }
        ]
      }
    },
    "D09": {
      "renju": {
        "depth": 18,
        "elapsedMs": 27259,
        "variations": [
          {
            "moves": [
              112,
              97,
              128,
              96,
              95,
              110
            ],
            "rank": 1,
            "score": "-265",
            "blackWinRate": 0.7900119999999999,
            "depth": 20,
            "analysisPly": 5,
            "id": "renju-1"
          },
          {
            "moves": [
              112,
              97,
              128,
              96,
              95,
              126
            ],
            "rank": 2,
            "score": "-265",
            "blackWinRate": 0.7900119999999999,
            "depth": 20,
            "analysisPly": 5,
            "id": "renju-2"
          },
          {
            "moves": [
              112,
              97,
              128,
              96,
              95,
              81
            ],
            "rank": 3,
            "score": "-270",
            "blackWinRate": 0.79413,
            "depth": 20,
            "analysisPly": 5,
            "id": "renju-3"
          }
        ]
      },
      "freestyle": {
        "depth": 22,
        "elapsedMs": 30040,
        "variations": [
          {
            "moves": [
              112,
              97,
              128,
              96,
              95,
              126
            ],
            "rank": 1,
            "score": "-398",
            "blackWinRate": 0.8797429999999999,
            "depth": 23,
            "analysisPly": 5,
            "id": "freestyle-1"
          },
          {
            "moves": [
              112,
              97,
              128,
              111,
              96,
              144
            ],
            "rank": 2,
            "score": "-572",
            "blackWinRate": 0.9458333,
            "depth": 22,
            "analysisPly": 3,
            "id": "freestyle-2"
          },
          {
            "moves": [
              112,
              97,
              128,
              96,
              95,
              110
            ],
            "rank": 2,
            "score": "-436",
            "blackWinRate": 0.898439,
            "depth": 23,
            "analysisPly": 5,
            "id": "freestyle-3"
          }
        ]
      }
    },
    "D10": {
      "renju": {
        "depth": 19,
        "elapsedMs": 30081,
        "variations": [
          {
            "moves": [
              112,
              97,
              129,
              96,
              114,
              111
            ],
            "rank": 1,
            "score": "-357",
            "blackWinRate": 0.856313,
            "depth": 19,
            "analysisPly": 3,
            "id": "renju-1"
          },
          {
            "moves": [
              112,
              97,
              129,
              98,
              128,
              144
            ],
            "rank": 2,
            "score": "-408",
            "blackWinRate": 0.884933,
            "depth": 19,
            "analysisPly": 3,
            "id": "renju-2"
          },
          {
            "moves": [
              112,
              97,
              129,
              126,
              143,
              111
            ],
            "rank": 3,
            "score": "-411",
            "blackWinRate": 0.886452,
            "depth": 19,
            "analysisPly": 3,
            "id": "renju-3"
          }
        ]
      },
      "freestyle": {
        "depth": 21,
        "elapsedMs": 30043,
        "variations": [
          {
            "moves": [
              112,
              97,
              129,
              96,
              99,
              83
            ],
            "rank": 1,
            "score": "-507",
            "blackWinRate": 0.9265593,
            "depth": 21,
            "analysisPly": 3,
            "id": "freestyle-1"
          },
          {
            "moves": [
              112,
              97,
              129,
              98,
              128,
              144
            ],
            "rank": 2,
            "score": "-507",
            "blackWinRate": 0.9265593,
            "depth": 21,
            "analysisPly": 3,
            "id": "freestyle-2"
          },
          {
            "moves": [
              112,
              97,
              129,
              126,
              143,
              111
            ],
            "rank": 3,
            "score": "-520",
            "blackWinRate": 0.9308616,
            "depth": 21,
            "analysisPly": 3,
            "id": "freestyle-3"
          }
        ]
      }
    },
    "D11": {
      "renju": {
        "depth": 18,
        "elapsedMs": 28900,
        "variations": [
          {
            "moves": [
              112,
              97,
              142,
              111,
              125,
              96
            ],
            "rank": 1,
            "score": "-453",
            "blackWinRate": 0.9059366,
            "depth": 23,
            "analysisPly": 5,
            "id": "renju-1"
          },
          {
            "moves": [
              112,
              97,
              142,
              96,
              98,
              126
            ],
            "rank": 2,
            "score": "-414",
            "blackWinRate": 0.887953,
            "depth": 18,
            "analysisPly": 3,
            "id": "renju-2"
          }
        ]
      },
      "freestyle": {
        "depth": 24,
        "elapsedMs": 30043,
        "variations": [
          {
            "moves": [
              112,
              97,
              142,
              111,
              125,
              96
            ],
            "rank": 1,
            "score": "-M32",
            "blackWinRate": 1,
            "depth": 33,
            "analysisPly": 5,
            "id": "freestyle-1"
          },
          {
            "moves": [
              112,
              97,
              142,
              96,
              98,
              126
            ],
            "rank": 2,
            "score": "-683",
            "blackWinRate": 0.96817,
            "depth": 24,
            "analysisPly": 3,
            "id": "freestyle-2"
          },
          {
            "moves": [
              112,
              97,
              142,
              111,
              125,
              127
            ],
            "rank": 2,
            "score": "-M28",
            "blackWinRate": 1,
            "depth": 33,
            "analysisPly": 5,
            "id": "freestyle-3"
          }
        ]
      }
    },
    "D12": {
      "renju": {
        "depth": 21,
        "elapsedMs": 28499,
        "variations": [
          {
            "moves": [
              112,
              97,
              143,
              141,
              128,
              96
            ],
            "rank": 1,
            "score": "-418",
            "blackWinRate": 0.889927,
            "depth": 21,
            "analysisPly": 3,
            "id": "renju-1"
          },
          {
            "moves": [
              112,
              97,
              143,
              98,
              96,
              127
            ],
            "rank": 2,
            "score": "-458",
            "blackWinRate": 0.9080454,
            "depth": 21,
            "analysisPly": 3,
            "id": "renju-2"
          },
          {
            "moves": [
              112,
              97,
              143,
              83,
              111,
              113
            ],
            "rank": 3,
            "score": "-508",
            "blackWinRate": 0.9268988,
            "depth": 21,
            "analysisPly": 3,
            "id": "renju-3"
          }
        ]
      },
      "freestyle": {
        "depth": 21,
        "elapsedMs": 30047,
        "variations": [
          {
            "moves": [
              112,
              97,
              143,
              83,
              111,
              113
            ],
            "rank": 1,
            "score": "-540",
            "blackWinRate": 0.9370266,
            "depth": 21,
            "analysisPly": 3,
            "id": "freestyle-1"
          },
          {
            "moves": [
              112,
              97,
              143,
              129,
              145,
              144
            ],
            "rank": 2,
            "score": "-585",
            "blackWinRate": 0.9490685,
            "depth": 21,
            "analysisPly": 3,
            "id": "freestyle-2"
          },
          {
            "moves": [
              112,
              97,
              143,
              111,
              125,
              129
            ],
            "rank": 3,
            "score": "-610",
            "blackWinRate": 0.9547825,
            "depth": 21,
            "analysisPly": 3,
            "id": "freestyle-3"
          }
        ]
      }
    },
    "D13": {
      "renju": {
        "depth": 20,
        "elapsedMs": 30070,
        "variations": [
          {
            "moves": [
              112,
              97,
              144,
              96,
              95,
              98
            ],
            "rank": 1,
            "score": "559",
            "blackWinRate": 0.05759499999999995,
            "depth": 22,
            "analysisPly": 5,
            "id": "renju-1"
          },
          {
            "moves": [
              112,
              97,
              144,
              111,
              83,
              126
            ],
            "rank": 2,
            "score": "205",
            "blackWinRate": 0.26405500000000004,
            "depth": 20,
            "analysisPly": 3,
            "id": "renju-2"
          },
          {
            "moves": [
              112,
              97,
              144,
              96,
              95,
              111
            ],
            "rank": 2,
            "score": "487",
            "blackWinRate": 0.080542,
            "depth": 22,
            "analysisPly": 5,
            "id": "renju-3"
          }
        ]
      },
      "freestyle": {
        "depth": 22,
        "elapsedMs": 28441,
        "variations": [
          {
            "moves": [
              112,
              97,
              144,
              111,
              83,
              81
            ],
            "rank": 1,
            "score": "-326",
            "blackWinRate": 0.83617,
            "depth": 23,
            "analysisPly": 5,
            "id": "freestyle-1"
          },
          {
            "moves": [
              112,
              97,
              144,
              111,
              83,
              128
            ],
            "rank": 2,
            "score": "-377",
            "blackWinRate": 0.8681840000000001,
            "depth": 23,
            "analysisPly": 5,
            "id": "freestyle-2"
          },
          {
            "moves": [
              112,
              97,
              144,
              111,
              83,
              126
            ],
            "rank": 3,
            "score": "-437",
            "blackWinRate": 0.898894,
            "depth": 23,
            "analysisPly": 5,
            "id": "freestyle-3"
          }
        ]
      }
    },
    "I01": {
      "renju": {
        "depth": 21,
        "elapsedMs": 30063,
        "variations": [
          {
            "moves": [
              112,
              98,
              84,
              83,
              68,
              100
            ],
            "rank": 1,
            "score": "-20",
            "blackWinRate": 0.524979,
            "depth": 21,
            "analysisPly": 3,
            "id": "renju-1"
          },
          {
            "moves": [
              112,
              98,
              84,
              97,
              83,
              85
            ],
            "rank": 2,
            "score": "-34",
            "blackWinRate": 0.5423979999999999,
            "depth": 21,
            "analysisPly": 3,
            "id": "renju-2"
          },
          {
            "moves": [
              112,
              98,
              84,
              82,
              114,
              99
            ],
            "rank": 3,
            "score": "-79",
            "blackWinRate": 0.597486,
            "depth": 21,
            "analysisPly": 3,
            "id": "renju-3"
          }
        ]
      },
      "freestyle": {
        "depth": 23,
        "elapsedMs": 28087,
        "variations": [
          {
            "moves": [
              112,
              98,
              84,
              97,
              96,
              128
            ],
            "rank": 1,
            "score": "-300",
            "blackWinRate": 0.817574,
            "depth": 23,
            "analysisPly": 3,
            "id": "freestyle-1"
          },
          {
            "moves": [
              112,
              98,
              84,
              83,
              68,
              100
            ],
            "rank": 2,
            "score": "-355",
            "blackWinRate": 0.855078,
            "depth": 23,
            "analysisPly": 3,
            "id": "freestyle-2"
          },
          {
            "moves": [
              112,
              98,
              84,
              82,
              114,
              128
            ],
            "rank": 3,
            "score": "-415",
            "blackWinRate": 0.888449,
            "depth": 23,
            "analysisPly": 3,
            "id": "freestyle-3"
          }
        ]
      }
    },
    "I02": {
      "renju": {
        "depth": 20,
        "elapsedMs": 30061,
        "variations": [
          {
            "moves": [
              112,
              98,
              99,
              113,
              128,
              129
            ],
            "rank": 1,
            "score": "-334",
            "blackWinRate": 0.841576,
            "depth": 20,
            "analysisPly": 3,
            "id": "renju-1"
          },
          {
            "moves": [
              112,
              98,
              99,
              114,
              82,
              97
            ],
            "rank": 2,
            "score": "-349",
            "blackWinRate": 0.851321,
            "depth": 20,
            "analysisPly": 3,
            "id": "renju-2"
          },
          {
            "moves": [
              112,
              98,
              99,
              82,
              113,
              114
            ],
            "rank": 3,
            "score": "-438",
            "blackWinRate": 0.899348,
            "depth": 20,
            "analysisPly": 3,
            "id": "renju-3"
          }
        ]
      },
      "freestyle": {
        "depth": 21,
        "elapsedMs": 30044,
        "variations": [
          {
            "moves": [
              112,
              98,
              99,
              127,
              83,
              128
            ],
            "rank": 1,
            "score": "-479",
            "blackWinRate": 0.9164452,
            "depth": 21,
            "analysisPly": 3,
            "id": "freestyle-1"
          },
          {
            "moves": [
              112,
              98,
              99,
              129,
              82,
              67
            ],
            "rank": 2,
            "score": "-552",
            "blackWinRate": 0.9404756,
            "depth": 21,
            "analysisPly": 3,
            "id": "freestyle-2"
          },
          {
            "moves": [
              112,
              98,
              99,
              113,
              128,
              129
            ],
            "rank": 3,
            "score": "-578",
            "blackWinRate": 0.9473499,
            "depth": 21,
            "analysisPly": 3,
            "id": "freestyle-3"
          }
        ]
      }
    },
    "I03": {
      "renju": {
        "depth": 18,
        "elapsedMs": 30074,
        "variations": [
          {
            "moves": [
              112,
              98,
              114,
              113,
              83,
              99
            ],
            "rank": 1,
            "score": "-317",
            "blackWinRate": 0.8299110000000001,
            "depth": 18,
            "analysisPly": 3,
            "id": "renju-1"
          },
          {
            "moves": [
              112,
              98,
              114,
              129,
              128,
              142
            ],
            "rank": 2,
            "score": "-344",
            "blackWinRate": 0.848129,
            "depth": 18,
            "analysisPly": 3,
            "id": "renju-2"
          },
          {
            "moves": [
              112,
              98,
              114,
              127,
              128,
              144
            ],
            "rank": 3,
            "score": "-364",
            "blackWinRate": 0.8605659999999999,
            "depth": 18,
            "analysisPly": 3,
            "id": "renju-3"
          }
        ]
      },
      "freestyle": {
        "depth": 24,
        "elapsedMs": 27321,
        "variations": [
          {
            "moves": [
              112,
              98,
              114,
              129,
              128,
              142
            ],
            "rank": 1,
            "score": "-527",
            "blackWinRate": 0.9330804,
            "depth": 24,
            "analysisPly": 3,
            "id": "freestyle-1"
          },
          {
            "moves": [
              112,
              98,
              114,
              113,
              83,
              99
            ],
            "rank": 2,
            "score": "-535",
            "blackWinRate": 0.9355352,
            "depth": 24,
            "analysisPly": 3,
            "id": "freestyle-2"
          },
          {
            "moves": [
              112,
              98,
              114,
              127,
              99,
              129
            ],
            "rank": 3,
            "score": "-584",
            "blackWinRate": 0.9488263,
            "depth": 24,
            "analysisPly": 3,
            "id": "freestyle-3"
          }
        ]
      }
    },
    "I04": {
      "renju": {
        "depth": 20,
        "elapsedMs": 30075,
        "variations": [
          {
            "moves": [
              112,
              98,
              129,
              114,
              130,
              128
            ],
            "rank": 1,
            "score": "-387",
            "blackWinRate": 0.873802,
            "depth": 20,
            "analysisPly": 3,
            "id": "renju-1"
          },
          {
            "moves": [
              112,
              98,
              129,
              111,
              128,
              97
            ],
            "rank": 2,
            "score": "-486",
            "blackWinRate": 0.9190865,
            "depth": 20,
            "analysisPly": 3,
            "id": "renju-2"
          },
          {
            "moves": [
              112,
              98,
              129,
              97,
              128,
              144
            ],
            "rank": 3,
            "score": "-509",
            "blackWinRate": 0.9272369,
            "depth": 20,
            "analysisPly": 3,
            "id": "renju-3"
          }
        ]
      },
      "freestyle": {
        "depth": 22,
        "elapsedMs": 30057,
        "variations": [
          {
            "moves": [
              112,
              98,
              129,
              114,
              130,
              128
            ],
            "rank": 1,
            "score": "-428",
            "blackWinRate": 0.8947309999999999,
            "depth": 22,
            "analysisPly": 3,
            "id": "freestyle-1"
          },
          {
            "moves": [
              112,
              98,
              129,
              97,
              128,
              144
            ],
            "rank": 2,
            "score": "-492",
            "blackWinRate": 0.9212897,
            "depth": 22,
            "analysisPly": 3,
            "id": "freestyle-2"
          },
          {
            "moves": [
              112,
              98,
              129,
              128,
              143,
              142
            ],
            "rank": 3,
            "score": "-522",
            "blackWinRate": 0.9315024,
            "depth": 22,
            "analysisPly": 3,
            "id": "freestyle-3"
          }
        ]
      }
    },
    "I05": {
      "renju": {
        "depth": 17,
        "elapsedMs": 30073,
        "variations": [
          {
            "moves": [
              112,
              98,
              144,
              96,
              99,
              114
            ],
            "rank": 1,
            "score": "29",
            "blackWinRate": 0.536187,
            "depth": 19,
            "analysisPly": 4,
            "id": "renju-1"
          },
          {
            "moves": [
              112,
              98,
              144,
              111,
              114,
              128
            ],
            "rank": 2,
            "score": "-87",
            "blackWinRate": 0.607067,
            "depth": 17,
            "analysisPly": 3,
            "id": "renju-2"
          }
        ]
      },
      "freestyle": {
        "depth": 22,
        "elapsedMs": 29188,
        "variations": [
          {
            "moves": [
              112,
              98,
              144,
              96,
              99,
              114
            ],
            "rank": 1,
            "score": "-344",
            "blackWinRate": 0.848129,
            "depth": 22,
            "analysisPly": 3,
            "id": "freestyle-1"
          },
          {
            "moves": [
              112,
              98,
              144,
              128,
              113,
              127
            ],
            "rank": 2,
            "score": "-466",
            "blackWinRate": 0.9113313,
            "depth": 22,
            "analysisPly": 3,
            "id": "freestyle-2"
          },
          {
            "moves": [
              112,
              98,
              144,
              111,
              99,
              96
            ],
            "rank": 3,
            "score": "-493",
            "blackWinRate": 0.9216515,
            "depth": 22,
            "analysisPly": 3,
            "id": "freestyle-3"
          }
        ]
      }
    },
    "I06": {
      "renju": {
        "depth": 19,
        "elapsedMs": 30067,
        "variations": [
          {
            "moves": [
              112,
              98,
              113,
              111,
              127,
              114
            ],
            "rank": 1,
            "score": "-290",
            "blackWinRate": 0.809998,
            "depth": 21,
            "analysisPly": 5,
            "id": "renju-1"
          },
          {
            "moves": [
              112,
              98,
              113,
              127,
              81,
              97
            ],
            "rank": 2,
            "score": "-301",
            "blackWinRate": 0.818319,
            "depth": 19,
            "analysisPly": 3,
            "id": "renju-2"
          },
          {
            "moves": [
              112,
              98,
              113,
              111,
              99,
              127
            ],
            "rank": 2,
            "score": "371",
            "blackWinRate": 0.864713,
            "depth": 21,
            "analysisPly": 4,
            "id": "renju-3"
          }
        ]
      },
      "freestyle": {
        "depth": 23,
        "elapsedMs": 30044,
        "variations": [
          {
            "moves": [
              112,
              98,
              113,
              127,
              96,
              111
            ],
            "rank": 1,
            "score": "-522",
            "blackWinRate": 0.9315024,
            "depth": 23,
            "analysisPly": 3,
            "id": "freestyle-1"
          },
          {
            "moves": [
              112,
              98,
              113,
              97,
              99,
              114
            ],
            "rank": 2,
            "score": "-559",
            "blackWinRate": 0.942405,
            "depth": 23,
            "analysisPly": 3,
            "id": "freestyle-2"
          },
          {
            "moves": [
              112,
              98,
              113,
              111,
              127,
              142
            ],
            "rank": 3,
            "score": "-572",
            "blackWinRate": 0.9458333,
            "depth": 23,
            "analysisPly": 3,
            "id": "freestyle-3"
          }
        ]
      }
    },
    "I07": {
      "renju": {
        "depth": 18,
        "elapsedMs": 29728,
        "variations": [
          {
            "moves": [
              112,
              98,
              128,
              96,
              129,
              99
            ],
            "rank": 1,
            "score": "1263",
            "blackWinRate": 0.998194,
            "depth": 23,
            "analysisPly": 4,
            "id": "renju-1"
          }
        ]
      },
      "freestyle": {
        "depth": 24,
        "elapsedMs": 27649,
        "variations": [
          {
            "moves": [
              112,
              98,
              128,
              96,
              129,
              111
            ],
            "rank": 1,
            "score": "+M49",
            "blackWinRate": 1,
            "depth": 24,
            "analysisPly": 4,
            "id": "freestyle-1"
          },
          {
            "moves": [
              112,
              98,
              128,
              96,
              114,
              142
            ],
            "rank": 2,
            "score": "+M61",
            "blackWinRate": 1,
            "depth": 24,
            "analysisPly": 4,
            "id": "freestyle-2"
          }
        ]
      }
    },
    "I08": {
      "renju": {
        "depth": 19,
        "elapsedMs": 30065,
        "variations": [
          {
            "moves": [
              112,
              98,
              143,
              127,
              141,
              130
            ],
            "rank": 1,
            "score": "-M42",
            "blackWinRate": 1,
            "depth": 25,
            "analysisPly": 5,
            "id": "renju-1"
          },
          {
            "moves": [
              112,
              98,
              143,
              142,
              128,
              129
            ],
            "rank": 2,
            "score": "-436",
            "blackWinRate": 0.898439,
            "depth": 19,
            "analysisPly": 3,
            "id": "renju-2"
          },
          {
            "moves": [
              112,
              98,
              143,
              127,
              141,
              142
            ],
            "rank": 2,
            "score": "-M36",
            "blackWinRate": 1,
            "depth": 25,
            "analysisPly": 5,
            "id": "renju-3"
          }
        ]
      },
      "freestyle": {
        "depth": 20,
        "elapsedMs": 30042,
        "variations": [
          {
            "moves": [
              112,
              98,
              143,
              96,
              129,
              111
            ],
            "rank": 1,
            "score": "-441",
            "blackWinRate": 0.9006976,
            "depth": 20,
            "analysisPly": 3,
            "id": "freestyle-1"
          },
          {
            "moves": [
              112,
              98,
              143,
              127,
              141,
              140
            ],
            "rank": 2,
            "score": "-473",
            "blackWinRate": 0.9141191,
            "depth": 20,
            "analysisPly": 3,
            "id": "freestyle-2"
          },
          {
            "moves": [
              112,
              98,
              143,
              128,
              129,
              157
            ],
            "rank": 3,
            "score": "-502",
            "blackWinRate": 0.9248399,
            "depth": 20,
            "analysisPly": 3,
            "id": "freestyle-3"
          }
        ]
      }
    },
    "I09": {
      "renju": {
        "depth": 18,
        "elapsedMs": 30067,
        "variations": [
          {
            "moves": [
              112,
              98,
              127,
              142,
              111,
              95
            ],
            "rank": 1,
            "score": "-402",
            "blackWinRate": 0.881843,
            "depth": 18,
            "analysisPly": 3,
            "id": "renju-1"
          },
          {
            "moves": [
              112,
              98,
              127,
              96,
              111,
              110
            ],
            "rank": 2,
            "score": "-434",
            "blackWinRate": 0.897523,
            "depth": 18,
            "analysisPly": 3,
            "id": "renju-2"
          },
          {
            "moves": [
              112,
              98,
              127,
              128,
              111,
              142
            ],
            "rank": 3,
            "score": "-441",
            "blackWinRate": 0.9006976,
            "depth": 18,
            "analysisPly": 3,
            "id": "renju-3"
          }
        ]
      },
      "freestyle": {
        "depth": 28,
        "elapsedMs": 28139,
        "variations": [
          {
            "moves": [
              112,
              98,
              127,
              96,
              97,
              82
            ],
            "rank": 1,
            "score": "-M42",
            "blackWinRate": 1,
            "depth": 28,
            "analysisPly": 3,
            "id": "freestyle-1"
          },
          {
            "moves": [
              112,
              98,
              127,
              142,
              111,
              128
            ],
            "rank": 2,
            "score": "-M40",
            "blackWinRate": 1,
            "depth": 28,
            "analysisPly": 3,
            "id": "freestyle-2"
          },
          {
            "moves": [
              112,
              98,
              127,
              111,
              141,
              142
            ],
            "rank": 3,
            "score": "-M40",
            "blackWinRate": 1,
            "depth": 28,
            "analysisPly": 3,
            "id": "freestyle-3"
          }
        ]
      }
    },
    "I10": {
      "renju": {
        "depth": 18,
        "elapsedMs": 30061,
        "variations": [
          {
            "moves": [
              112,
              98,
              142,
              97,
              96,
              128
            ],
            "rank": 1,
            "score": "-381",
            "blackWinRate": 0.870456,
            "depth": 18,
            "analysisPly": 3,
            "id": "renju-1"
          },
          {
            "moves": [
              112,
              98,
              142,
              96,
              110,
              126
            ],
            "rank": 2,
            "score": "-465",
            "blackWinRate": 0.9109265,
            "depth": 18,
            "analysisPly": 3,
            "id": "renju-2"
          },
          {
            "moves": [
              112,
              98,
              142,
              127,
              128,
              99
            ],
            "rank": 3,
            "score": "-515",
            "blackWinRate": 0.9292352,
            "depth": 18,
            "analysisPly": 3,
            "id": "renju-3"
          }
        ]
      },
      "freestyle": {
        "depth": 22,
        "elapsedMs": 27414,
        "variations": [
          {
            "moves": [
              112,
              98,
              142,
              97,
              96,
              128
            ],
            "rank": 1,
            "score": "-M54",
            "blackWinRate": 1,
            "depth": 31,
            "analysisPly": 5,
            "id": "freestyle-1"
          },
          {
            "moves": [
              112,
              98,
              142,
              96,
              99,
              113
            ],
            "rank": 2,
            "score": "-543",
            "blackWinRate": 0.937906,
            "depth": 22,
            "analysisPly": 3,
            "id": "freestyle-2"
          },
          {
            "moves": [
              112,
              98,
              142,
              97,
              96,
              126
            ],
            "rank": 2,
            "score": "-M24",
            "blackWinRate": 1,
            "depth": 31,
            "analysisPly": 5,
            "id": "freestyle-3"
          }
        ]
      }
    },
    "I11": {
      "renju": {
        "depth": 18,
        "elapsedMs": 30070,
        "variations": [
          {
            "moves": [
              112,
              98,
              126,
              97,
              99,
              83
            ],
            "rank": 1,
            "score": "-149",
            "blackWinRate": 0.678088,
            "depth": 20,
            "analysisPly": 5,
            "id": "renju-1"
          }
        ]
      },
      "freestyle": {
        "depth": 24,
        "elapsedMs": 28170,
        "variations": [
          {
            "moves": [
              112,
              98,
              126,
              97,
              95,
              128
            ],
            "rank": 1,
            "score": "483",
            "blackWinRate": 0.917964,
            "depth": 24,
            "analysisPly": 4,
            "id": "freestyle-1"
          },
          {
            "moves": [
              112,
              98,
              126,
              97,
              110,
              113
            ],
            "rank": 2,
            "score": "462",
            "blackWinRate": 0.909702,
            "depth": 24,
            "analysisPly": 4,
            "id": "freestyle-2"
          },
          {
            "moves": [
              112,
              98,
              126,
              97,
              99,
              114
            ],
            "rank": 3,
            "score": "446",
            "blackWinRate": 0.902911,
            "depth": 24,
            "analysisPly": 4,
            "id": "freestyle-3"
          }
        ]
      }
    },
    "I12": {
      "renju": {
        "depth": 18,
        "elapsedMs": 30074,
        "variations": [
          {
            "moves": [
              112,
              98,
              141,
              113,
              142,
              97
            ],
            "rank": 1,
            "score": "-M48",
            "blackWinRate": 1,
            "depth": 28,
            "analysisPly": 5,
            "id": "renju-1"
          },
          {
            "moves": [
              112,
              98,
              141,
              83,
              96,
              128
            ],
            "rank": 2,
            "score": "-348",
            "blackWinRate": 0.850687,
            "depth": 18,
            "analysisPly": 3,
            "id": "renju-2"
          },
          {
            "moves": [
              112,
              98,
              141,
              113,
              142,
              96
            ],
            "rank": 2,
            "score": "-M24",
            "blackWinRate": 1,
            "depth": 28,
            "analysisPly": 5,
            "id": "renju-3"
          }
        ]
      },
      "freestyle": {
        "depth": 20,
        "elapsedMs": 30051,
        "variations": [
          {
            "moves": [
              112,
              98,
              141,
              114,
              142,
              99
            ],
            "rank": 1,
            "score": "+M29",
            "blackWinRate": 1,
            "depth": 24,
            "analysisPly": 4,
            "id": "freestyle-1"
          },
          {
            "moves": [
              112,
              98,
              141,
              113,
              143,
              129
            ],
            "rank": 2,
            "score": "-456",
            "blackWinRate": 0.907207,
            "depth": 20,
            "analysisPly": 3,
            "id": "freestyle-2"
          },
          {
            "moves": [
              112,
              98,
              141,
              114,
              127,
              142
            ],
            "rank": 2,
            "score": "+M39",
            "blackWinRate": 1,
            "depth": 24,
            "analysisPly": 4,
            "id": "freestyle-3"
          }
        ]
      }
    },
    "I13": {
      "renju": {
        "depth": 22,
        "elapsedMs": 27414,
        "variations": [
          {
            "moves": [
              112,
              98,
              140,
              83,
              113,
              114
            ],
            "rank": 1,
            "score": "576",
            "blackWinRate": 0.05315099999999995,
            "depth": 21,
            "analysisPly": 5,
            "id": "renju-1"
          },
          {
            "moves": [
              112,
              98,
              140,
              82,
              142,
              114
            ],
            "rank": 2,
            "score": "464",
            "blackWinRate": 0.08948,
            "depth": 22,
            "analysisPly": 3,
            "id": "renju-2"
          },
          {
            "moves": [
              112,
              98,
              140,
              83,
              113,
              99
            ],
            "rank": 2,
            "score": "479",
            "blackWinRate": 0.08355500000000005,
            "depth": 21,
            "analysisPly": 5,
            "id": "renju-3"
          }
        ]
      },
      "freestyle": {
        "depth": 23,
        "elapsedMs": 27866,
        "variations": [
          {
            "moves": [
              112,
              98,
              140,
              83,
              99,
              82
            ],
            "rank": 1,
            "score": "53",
            "blackWinRate": 0.565865,
            "depth": 22,
            "analysisPly": 4,
            "id": "freestyle-1"
          },
          {
            "moves": [
              112,
              98,
              140,
              83,
              113,
              114
            ],
            "rank": 1,
            "score": "0",
            "blackWinRate": 0.5,
            "depth": 27,
            "analysisPly": 5,
            "id": "freestyle-2"
          },
          {
            "moves": [
              112,
              98,
              140,
              83,
              113,
              99
            ],
            "rank": 2,
            "score": "-41",
            "blackWinRate": 0.551071,
            "depth": 27,
            "analysisPly": 5,
            "id": "freestyle-3"
          }
        ]
      }
    }
  }
};
